---
title: "Implementing the daily-drinking-notebook"
<!-- --- -->


## Setting up 
```{r, output=FALSE}
getwd()
```
```{r}

if (!require("pacman")) 
  install.packages("pacman")

pacman::p_load("statmod",
"mvtnorm",
"Matrix", 
"splines",
"xtable",
"IRdisplay",
"repr",
"plotly",
"extrafont",
"ggplot2",
"gridExtra",
"grid",
"table1",
"coda",
"rstanarm",
"bayesplot")
```

## Loading Data

```{r}
rm(list=ls()) # cleans memory

load("Mixed.SVM-main/data/processed/example.RData")

```


```{r}
head(drinks)
```

## Model Implementation

```{r}

# set up for plotting figures
options(bitmapType="cairo") #linux

#options(bitmapType="quartz") # mac


set.seed(2) #sets a seed for random number generators used by the algorithm
```

```{r}
source("Mixed.SVM-main/src/R/mixed-svm.R")

# source('src/R/mixed-svm.R')

```

```{r}
Y <- as.vector(drinks$HD) # outcome
X <- as.matrix(drinks[,c("male","age","NICUSEDAY","THCUSEDAY","OTHERDRUGUSE")]) # covariates
T <- as.vector(drinks$Day) # times
U <- as.vector(drinks$ursi) # individual id
Tmax <- 720
knot.seq <- c(0.5)
# Iter <- 100000
Iter <- 1000
burn.in <- 50000
     
```

```{r}

# Runs the algorithm
# Remove # to run
# MCMC.res <- Mixed.SVM(Y, X, T, U, Tmax, knot.seq, Iter)

# Saves the results
# Remove # to run
# save(MCMC.res,file='Mixed.SVM-main/reports/demo-results1k.RData')

# Here we pull up previously saved results
# load(file='Mixed.SVM-main/reports/demo-results1k.RData')
```


## Results

### 100 Iterations

```{r}
# Loading the results
load(file='Mixed.SVM-main/reports/demo-results100.RData')
```


```{r}
# Understanding Dimensions and other parameters of the output 

str(MCMC.res$Beta)

dim(MCMC.res$Beta)

dimnames(MCMC.res$Beta)



# Trace plots

# mcmc_trace(MCMC.res$Beta) --> Error in `parameter_names()`

# Adding column names to the "Beta" matrix to avoid the above error
colnames(MCMC.res$Beta) <- c("beta_male","beta_age","beta_NICUSEDAY","beta_THCUSEDAY","beta_OTHERDRUGUSE")
mcmc_trace(as.array(MCMC.res$Beta))

```


### 1000 Iterations

```{r}
# Loading the results
load(file='Mixed.SVM-main/reports/demo-results1k.RData')
```


```{r}
# Understanding Dimensions and other parameters of the output 

str(MCMC.res$Beta)

dim(MCMC.res$Beta)

dimnames(MCMC.res$Beta)



# Trace plots

# mcmc_trace(MCMC.res$Beta) --> Error in `parameter_names()`

# Adding column names to the "Beta" matrix to avoid the above error
colnames(MCMC.res$Beta) <- c("beta_male","beta_age","beta_NICUSEDAY","beta_THCUSEDAY","beta_OTHERDRUGUSE")
mcmc_trace(as.array(MCMC.res$Beta))
```



### 10000 Iterations

```{r}
# Loading the results
load(file='Mixed.SVM-main/reports/demo-results10k.RData')
```


```{r}
# Understanding Dimensions and other parameters of the output 

str(MCMC.res$Beta)

dim(MCMC.res$Beta)

dimnames(MCMC.res$Beta)



# Trace plots

# mcmc_trace(MCMC.res$Beta) --> Error in `parameter_names()`

# Adding column names to the "Beta" matrix to avoid the above error
colnames(MCMC.res$Beta) <- c("beta_male","beta_age","beta_NICUSEDAY","beta_THCUSEDAY","beta_OTHERDRUGUSE")
mcmc_trace(as.array(MCMC.res$Beta))
```

